name: Exo workflow
on: push
jobs:
  first_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code
        uses: actions/checkout@v4
      - name: install dépendances
        run: npm install
      - name: build
        run: npm run build
      # - name: Déploiement du projet
      #   run: echo "En cours de déploiement..."
      - name: Upload le résultat du build
        uses: actions/upload-artifact@v4
        with:
          name: mon-site
          path: .next/
