name: s'éxecute lors d'une pull request
on:
  pull_request:
    types: opened # C'est une des acitivtés par défaut
jobs:
  job-ex:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Il y a une pull request again"
